name: 'export-git-proof'
description: 'Export proof of the state of a git repo'
author: 'David Barri (@japgolly)'

branding:
  icon: "arrow-down"
  color: "purple"

# ======================================================================================================================
inputs:

  gist_id:
    description: "id of the gist"
    required: true

# ======================================================================================================================
runs:
  using: 'composite'
  steps:

    - name: Read gist
      id: gist_content
      uses: gorgbus/gist-actions@main
      with:
        action: "get"
        gist_id: "53838ce9fdf74882096c3e59bff2f566"
        file_name: "log.txt"

    - name: omg programming
      shell: bash
      run: "echo 'meta.json content: ${{ steps.gist_content.outputs.content }}'"
