name: 'export-git-proof'
description: 'Export proof of the state of a git repo'
author: 'David Barri (@japgolly)'

branding:
  icon: "arrow-down"
  color: "purple"

# ======================================================================================================================
inputs:

  gist_id:
    description: "id of the gist"
    required: true

# ======================================================================================================================
runs:
  using: 'composite'
  steps:

    - name: Get git log
      id: log
      shell: bash
      run: |
        echo "LOG_OUTPUT<<EOF" >> $GITHUB_ENV
        git log --stat >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Update gist
      uses: gorgbus/gist-actions@main
      with:
        action: update
        gist_id: ${{ inputs.gist_id }}
        file_name: log.txt
        content: ${{ env.LOG_OUTPUT }}
