name: 'export-git-proof'
description: 'Export proof of the state of a git repo'
author: 'David Barri (@japgolly)'

branding:
  icon: "arrow-down"
  color: "purple"

# ======================================================================================================================
inputs:

  token:
    description: "Access token for updating gist"
    required: true

  gist_id:
    description: "id of the gist"
    required: true

# ======================================================================================================================
runs:
  using: 'composite'
  steps:

    - name: Get git log
      id: log
      shell: bash
      run: |
        git log --stat > .....GIT_LOG.txt

    - name: Update gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ inputs.token }}
        gist_id: ${{ inputs.gist_id }}
        gist_file_name: log.txt
        file_path: .....GIT_LOG.txt
